
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'fr'}];
  }
  export default function RootLayout({
    children, params: {locale},
    }: {
    children: React.ReactNode,
    params: any
    })  
  {
    return (
      <div lang={locale}>
        <div>{children}</div>
      </div>
    )
  }