'use client'
import './globals.css'
import type { Metadata } from 'next'

import ThemeSwitcher from './components/ThemeSwitcher'
import Navbar from './components/Navbar'
import { Poppins } from 'next/font/google'
import Background from './components/Background'

import Providers from './providers'
import ToasterContext from './context/ToasterContext'
import { SessionProvider } from 'next-auth/react';

import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import LangSwitcher from './components/Links/LangSwitcher'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'fr'}];
}

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default async function RootLayout({
  children, params: {locale},
}: {
  children: React.ReactNode,
  params: any
}) {
  
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <SessionProvider>
      <NextIntlClientProvider locale={locale} messages={messages}>
    <html >
        <body className={`${poppins.className} dark:bg-dark bg-light`}>
          
          <main>
            <Background />
            <Providers> 
              <Navbar />
              <ToasterContext/>
              <ThemeSwitcher />
              <LangSwitcher className='fixed right-3 bottom-20'/>
              
              {children}
            </Providers>
          </main>
        </body>
    </html>
    </NextIntlClientProvider>
    </SessionProvider>
  )
}
