import Title from "./components/Texts/Title";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default function Home() {

  return (
    <div>
      <Title text="Notify" className='mb-16
      lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl lg:gap-8 md:gap-y-16'/>
    </div>
  );
  
}
